udistrital/movimientos_crud

- controllers/movimiento.go
- controllers/movimiento_detalle.go
- controllers/tipo_movimiento.go
- models/movimiento.go
- models/movimiento_detalle.go
- models/tipo_movimiento.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
> #1 Feature/models and controllers

- README.md
se actualiza licencia y documentacion del README
> #6 update README.md

- database/migrations/20190620_233222_crear_schema_movimientos.go
Se modificio la linea que crea el esquema agregando IF NOT EXIST
> Corrigiendo migraciones:

- database/migrations/20190704_152011_insertar_tipo_movimiento_traslado.go
se agrega la migracion que crea el tipo de movimiento traslado entre dos fuentes de financiamiento #11
> se añade migración movimiento traslado 

- controllers/movimiento_proceso_externo.go
- database/migrations/20190728_182441_agregar_campos_fechas_activo.go
- docker-compose.yml
- models/movimiento_detalle.go
- models/movimiento_proceso_externo.go
- models/tipo_movimiento.go
- swagger/swagger.json
se agregan los campos (activo,fecha_creacion y fecha_modificacion) a la migracion y al modelo del api
> #26 add fields movimientos

- database/migrations/20190924_210421_insertar_tipos_movimiento_cdp_rp.go
https://github.com/udistrital/plan_cuentas_mongo_crud/issues/100
> Se agrega migración de tipos para cdp y rp

- .drone.yml
> Ajuste de espacios en blanco del archivo .drone.yml

- main.go
>  Se agrega el apistatus

- database/migrations/20191204_115505_tipos_movimiento_fuente.go
[Issue #39](https://github.com/udistrital/plan_cuentas_mid/issues/39)
> resolve migrations movements

- database/migrations/20191204_115505_tipos_movimiento_fuente.go
se agregan parametros para propagación a rubros.
[Issue #128](https://github.com/udistrital/presupuesto_cliente/issues/128) Mod Fuentes
> se retira traslado y se agrega retiro

- database/migrations/20191204_115505_tipos_movimiento_fuente.go
- docker-compose.yml
[Issue #128](https://github.com/udistrital/presupuesto_cliente/issues/128) Mod Fuentes
> Dev -> Test Dec 19 Migration reducción fuente

- main.go
[Issue #47](https://github.com/udistrital/financiera_documentacion/issues/47)
> Dev -> Test Dec 19 Se agrega auditoria

- database/files/insert_tipomovimiento_desarrollo_intangible.up.sql
- database/migrations/20210128_114137_insert_entrada_desarrollo_intangible.go
Insert de entrada registrada en la HU. udistrital/arka_cliente#459
> feature:Insert a tipo de entrada Intangibles desarrollados 

- .drone.yml
Reverts udistrital/movimientos_crud#85
> Revert "feat: cambio de imagen"

- README.md
Tiene que ver con: udistrital/presupuesto_cliente#468
> Ajustes README release/0.3.0

- .drone.yml
- README.md
- go.mod
- go.sum
Tiene que ver con udistrital/presupuesto_cliente#468
> docs: release/0.4.0

- helpers/crearMovimientoDetalle.go
- helpers/obtenerMovimiento.go
- helpers/ultimoMovimientoDetallePublicado.go
Tiene que ver con: udistrital/presupuesto_cliente#468
> feature: Publicacion de movimientos detalle para una necesidad entrante

- README.md
Tiene que ver con: udistrital/presupuesto_cliente#468
> docs: README release/0.5.2

- controllers/movimiento_detalle.go
- helpers/crearMovimientoDetalle.go
- helpers/publicarMovimientoDetalle.go
- helpers/ultimoMovimientoDetalle.go
- helpers/ultimoMovimientoDetallePublicado.go
Queda pendiente revisar por que esta trayendo los movimientos publicados de otros planes y evitar que eso suceda
Resuelve: udistrital/plan_adquisiciones_cliente#95
> refactor: Modificaciones para publicar nueva version del plan

- README.md
Resuelve: udistrital/plan_adquisiciones_cliente#95
> docs: Actualizacion README release/0.5.3

- controllers/movimiento_detalle.go
- controllers/movimiento_proceso_externo.go
- controllers/tipo_movimiento.go
- go.mod
- go.sum
- main.go
- managers/movimientoProcesoExternoManager/registrar_movimiento_manager.go
- models/all_modelos.go
- swagger/swagger.json
- swagger/swagger.yml
https://github.com/udistrital/necesidades_cliente/issues/306
> feat: Cambios conexion base de datos

- .drone.yml
- README.md
Resuelve: udistrital/financiera_documentacion#411
> docs: README release/1.1.0

- helpers/ultimoMovimientoDetalle.go
- main.go
Resuelve: udistrital/financiera_documentacion#411
> fix: Cambio de tipo de dato de la ActividadId buscada a string

- helpers/crearMovimientoDetalle.go
- helpers/publicarMovimientoDetalle.go
- helpers/ultimoMovimientoDetalle.go
- models/all_modelos.go
- models/movimiento_proceso_externo.go
- swagger/swagger.json
- swagger/swagger.yml
https://github.com/udistrital/financiera_documentacion/issues/444
> Feature/Refactor de Crear Movimiento Detalle

- helpers/crearMovimientoDetalle.go
- helpers/ultimoMovimientoDetalle.go
- models/all_modelos.go
https://github.com/udistrital/financiera_documentacion/issues/444
> fix: Cambio nombre campo Cuen_Pre

- README.md
- helpers/ultimoMovimientoDetallePublicado.go
https://github.com/udistrital/financiera_documentacion/issues/444
> Release to Develop
